django_application/urls.py
"""project_settings URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import about, index, predict_page,cuda_full

app_name = 'ml_app'
handler404 = views.handler404

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),
    path('predict/', predict_page, name='predict'),
    path('cuda_full/',cuda_full,name='cuda_full'),
]

django_application/templates/about.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
{%endblock%}

django_application/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="/static/bootstrap/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
    <link rel="stylesheet" href="/static/css/jquery-ui.css">

    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <title>Deepfake Detection</title>
</head>
<body>
    {%include 'nav-bar.html'%}
    {%block content%}
    {%endblock%}
    <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script> -->
        <script src="/static/js/jquery-3.4.1.min.js" ></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script> -->
        <script src="/static/js/popper.min.js"></script>
    <!-- <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script> -->
        <script src="/static/js/jquery-ui.min.js"></script>
    
        {%block js_cripts%}
    {%endblock%}
    {%include 'footer.html'%}
</body>

</html>

django_application/templates/footer.html
<footer class="footer">
    <div class="container">
      <center><span class="text-muted" >Copyright @ {%now 'Y'%}</span></center>
      <!-- <a href="{% url 'ml_app:home'%}">Home</a>
      <a href="{% url 'ml_app:about'%}">About</a>
      <a href="#">Github Link</a> -->
    </div>
  </footer>

django_application/templates/index.html
{% extends 'base.html' %}
{%load static%}
{%block content%}
<div class="bg" >
<div class="container">
    
    <div class="row align-items-center justify-content-center">
        <div class="col-12 my-auto">
            <div class="logo text-center mb-3"><img src="{% static 'images/logo1.png'%}" alt="Logo" ></div>
            <div class="width-400">
                <video width="100%" controls id="videos">
                    <source src="" id="video_source">
                    Your browser does not support HTML5 video.
                </video>
                <form class="form" method="POST" enctype="multipart/form-data" name="video-upload" id="video-upload"
                    class="text-center mt-3">
                    {%csrf_token%}
                    <div class="form-group">
                        <label>{{form.upload_video_file.widget}}</label>
                        {{form.upload_video_file}}
                        <!-- <input type="file" id="{{form.upload_video_file.id_for_label}}" name="{{form.upload_video_file.name}}" /> -->
                        {%if form.upload_video_file.errors%}
                        {%for each_error in form.upload_video_file.errors%}
                        <div class="alert alert-danger mt-1 {{form.upload_video_file.id_for_label}}">
                            {{each_error}}
                        </div>
                        {%endfor%}
                        {%endif%}
                    </div>
                    <div class="form-group">
                        <label for="{{form.sequence_length.id_for_label}}">{{form.sequence_length.label}}: </label><span
                            id="slider-value"></span>
                        <input type="number" hidden="hidden" id="{{form.sequence_length.id_for_label}}"
                            name="{{form.sequence_length.name}}"></input>
                        <div id='slider'></div>
                        {%if form.sequence_length.errors%}
                        {%for each_error in form.sequence_length.errors%}
                        <div class="alert alert-danger mt-1 {{form.sequence_length.id_for_label}}">
                            {{each_error}}
                        </div>
                        {%endfor%}
                        {%endif%}
                    </div>
                    <button id="videoUpload" type="submit" name="submit" class="btn btn-success mt-3 btn-block">Upload</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{%endblock%}
{%block js_cripts%}
<script src="{%static 'js/script.js'%}"></script>
<script>
    $(function () {
        var sliderSequenceNumbers = [10,20,40,60,80,100];
        var slider = $("div#slider").slider({
            value: 1,
            min: 0,
            max: sliderSequenceNumbers.length-1,
            slide: function (event, ui) {
                $('#{{form.sequence_length.id_for_label}}').val(sliderSequenceNumbers[ui.value]);
                $('#{{form.sequence_length.id_for_label}}').val(sliderSequenceNumbers[ui.value]);
                $('#slider-value').html(sliderSequenceNumbers[ui.value]);
            }
        });
        $("#{{form.sequence_length.id_for_label}}").val(sliderSequenceNumbers[$("#slider").slider("value")]);
        $('#slider-value').html(sliderSequenceNumbers[$("#slider").slider("value")]);
    });
</script>
{%endblock%}

django_application/templates/nav-bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'ml_app:home'%}">Home</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="{%url 'ml_app:about'%}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">GitHub</a>
            </li> -->
        </ul>
    </div>
</nav>

django_application/templates/predict.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
{%if no_faces%}
<div class="container">
  <div class="logo text-center mb-3"><img src="{% static 'images/logo1.png'%}" alt="Logo" ></div>
  <hr />
  <div class="alert alert-danger">
    No faces detected. Cannot process the video.
  </div>
</div>
{%else%}
<div class="container">
  <div class="logo text-center mb-3"><img src="{% static 'images/logo1.png'%}" alt="Logo" ></div>
  <hr />

  <h3>Frames Split</h3>
  <div id="preprocessed_images" class="col-12 mt-4 mb-2">
    {% for each_image in preprocessed_images %}
    <img src="{%static each_image%}" class="preprocess" width=auto height="250" />
    {%endfor%}
  </div>


  <h3>Face Cropped Frames</h3>
  <div id="faces_images" class="col-12 mb-2">
    {% for each_image in faces_cropped_images %}
    <img src="{%static each_image%}" class="faces" width=auto height="150" />
    {%endfor%}
  </div>

  <div class="result text-center">
    <h3>Play to see Result</h3>
    <video height="320" width="640" id="predict-media" controls>
      <source src="{{MEDIA_URL}}{{original_video}}" type="video/mp4" codecs="avc1.4d002a" />
    </video>
    {%if output == "REAL" %}
    <h4 class="mx-auto">Result: <span style="color:green">{{output}}</span>
      <img src="{% static 'images/thumpup.png'%}" alt="real" height="100px" width=auto>
      {%else%}
      <h4 class="mx-auto">Result: <span style="color:red">{{output}}</span>
        <img src="{% static 'images/thumpdown.png'%}" alt="fake" height="100px" width=auto >
      {%endif%}
  </div>
<!--
  <h3>Heat Maps</h3>
  <div id="heatmap_images" class="col-12 mb-4 ">
    {% for each_heatmap_image in heatmap_images %}
    <img src="{%static each_heatmap_image%}" class="heat-map" width="100" height="150" />
    {%endfor%}
  </div>
</div>
-->
{%endif%}
{%endblock%}
{%block js_cripts%}
<script src="{%static 'js/face-api.min.js'%}"></script>
<script>
  $(document).ready(function () {
    const video = document.getElementById("predict-media");

    Promise.all([
    faceapi.nets.ssdMobilenetv1.loadFromUri('/static/json'),
      faceapi.nets.tinyFaceDetector.loadFromUri("/static/json")
      
    ])

    var detectionTimeout;
    video.addEventListener("playing", () => {
      var canvas;
      if ($('canvas').length < 1) {
        canvas = faceapi.createCanvasFromMedia(video);
        canvas.style.top = video.offsetTop + "px";
        canvas.style.left = video.offsetLeft + "px";
        document.body.append(canvas);
      }
      /* In order to be able to pause the video */
      const displaySize = { width: video.width, height: video.height - 60 };
      faceapi.matchDimensions(canvas, displaySize);

      detectionTimeout = setInterval(async () => {
        const detections = await faceapi.detectAllFaces(video);
        const resizedDetections = faceapi.resizeResults(detections, displaySize);
        canvas.getContext("2d").clearRect(0, 0, canvas.width, canvas.height);
        canvas.style.top = video.offsetTop + "px";
        canvas.style.left = video.offsetLeft + "px";
        resizedDetections.forEach((result, i) => {
          console.log(resizedDetections[i].box);
          var result = '{{output}}';
          var confidence = '{{confidence}}';
          var drawOptions = {label: result.concat("  " , confidence , "%")};
          if (result == 'REAL'){
            drawOptions["boxColor"] = "#0f0";
          }
          else if (result == 'FAKE'){
            drawOptions["boxColor"] = "#f00";
          }
          var box = { x: resizedDetections[i].box.x, y: resizedDetections[i].box.y, height: 100, width: 100 };
          const drawBox = new faceapi.draw.DrawBox(box, drawOptions);
          drawBox.draw(canvas);
        });
      }, 1);
    });

    video.addEventListener("paused", () => {
      clearTimeout(detectionTimeout);
    });
  })
</script>
{%endblock%}